import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./component/Navbar";
import {
    ApolloClient,
    InMemoryCache,
    ApolloProvider,
    gql,
} from "@apollo/client";

const inter = Inter({ subsets: ["latin"] });

const client = new ApolloClient({
    uri: "https://wpe-hiring.tokopedia.net/graphql",
    cache: new InMemoryCache(),
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ApolloProvider client={client}>
                    <Navbar />
                    {children}
                </ApolloProvider>
            </body>
        </html>
    );
}
